apiVersion: apps/v1
kind: Deployment
metadata:
  name: <YOUR-PGBOUNCER-DEPLOYMENT-NAME>
spec:
  selector:
    matchLabels:
      app: <YOUR-PGBOUNCER-NAME>
  template:
    metadata:
      labels:
        app: <YOUR-PGBOUNCER-NAME>
    spec:
      serviceAccountName: <YOUR-KSA-NAME>
      volumes:
      - name: cacert
        secret:
          secretName: <YOUR-CA-SECRET>
          items:
          - key: tls.crt
            path: cert.pem
      - name: servercert
        secret:
          secretName: <YOUR-SERVER-CERT-SECRET>
          items:
          - key: tls.crt
            path: cert.pem
          - key: tls.key
            path: key.pem
      containers:
      - name: pgbouncer
        image: <PG-BOUNCER-CONTAINER>
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: cacert
          mountPath: "/etc/ca"
          readOnly: true
        - name: servercert
          mountPath: "/etc/server"
          readOnly: true
        env:
        - name: DB_HOST
          value: "127.0.0.1"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: <YOUR-DB-SECRET>
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: <YOUR-DB-SECRET>
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: <YOUR-DB-SECRET>
              key: database
        - name: DB_PORT
          value: "5431"
        - name: CLIENT_TLS_SSLMODE
          value: "require"
        - name: CLIENT_TLS_CA_FILE
          value: "/etc/ca/cert.pem"
        - name: CLIENT_TLS_KEY_FILE
          value: "/etc/server/key.pem"
        - name: CLIENT_TLS_CERT_FILE
          value: "/etc/server/cert.pem"
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.22.0
        command:
          - "/cloud_sql_proxy"
          - "-instances=<INSTANCE_CONNECTION_NAME>=tcp:5431"
        securityContext:
          runAsNonRoot: true
